/**
 * Known audit action names. Stored as a plain string column in the database
 * (see DATABASE.md — deliberately NOT a Postgres enum) so new actions never
 * require a migration. This const list is the app-level contract new code
 * should draw from instead of inventing ad-hoc strings.
 */
export const AUDIT_ACTIONS = {
  USER_INVITED: "USER_INVITED",
  USER_ACTIVATED: "USER_ACTIVATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DISABLED: "USER_DISABLED",
  USER_REACTIVATED: "USER_REACTIVATED",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
  USER_LOGOUT: "USER_LOGOUT",
  USER_LOGOUT_ALL: "USER_LOGOUT_ALL",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",
  ROLE_ASSIGNED: "ROLE_ASSIGNED",
  ROLE_REVOKED: "ROLE_REVOKED",
  DEPARTMENT_CREATED: "DEPARTMENT_CREATED",
  DEPARTMENT_UPDATED: "DEPARTMENT_UPDATED",
  DEPARTMENT_DELETED: "DEPARTMENT_DELETED",
  TEAM_CREATED: "TEAM_CREATED",
  TEAM_UPDATED: "TEAM_UPDATED",
  TEAM_DELETED: "TEAM_DELETED",
  TEAM_MEMBER_ADDED: "TEAM_MEMBER_ADDED",
  TEAM_MEMBER_REMOVED: "TEAM_MEMBER_REMOVED",
  ORGANIZATION_UPDATED: "ORGANIZATION_UPDATED",
  SECURITY_REFRESH_REUSE_DETECTED: "SECURITY_REFRESH_REUSE_DETECTED",

  // Phase 2 — tasks
  TASK_CREATED: "TASK_CREATED",
  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_UNASSIGNED: "TASK_UNASSIGNED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_COMPLETED: "TASK_COMPLETED",
  TASK_DELETED: "TASK_DELETED",
  TASK_COMMENT_CREATED: "TASK_COMMENT_CREATED",
  TASK_COMMENT_DELETED: "TASK_COMMENT_DELETED",
  TASK_ATTACHMENT_ADDED: "TASK_ATTACHMENT_ADDED",
  TASK_ATTACHMENT_REMOVED: "TASK_ATTACHMENT_REMOVED",
  FILE_UPLOADED: "FILE_UPLOADED",
  FILE_DELETED: "FILE_DELETED",

  // Phase 3 — events & reminders
  EVENT_CREATED: "EVENT_CREATED",
  EVENT_UPDATED: "EVENT_UPDATED",
  EVENT_DELETED: "EVENT_DELETED",
  EVENT_PARTICIPANT_ADDED: "EVENT_PARTICIPANT_ADDED",
  EVENT_PARTICIPANT_REMOVED: "EVENT_PARTICIPANT_REMOVED",
  EVENT_RSVP_UPDATED: "EVENT_RSVP_UPDATED",
  REMINDER_CREATED: "REMINDER_CREATED",
  REMINDER_DELETED: "REMINDER_DELETED",
} as const;

export type AuditActionName = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
